### PR TITLE
Why are there any differences? 

### PR DESCRIPTION
**Pull request by mlworle**
This branch was just created after the successful merge of mw-styles. Now, there is weird code in routes.rb and errors all across the board? Wha?

### CODE REVIEW

**Comment by edwardloveall** [comment]
It looks like there were some problems rebasing. Did you start this branch before merging in `mw-styles`?  I'm not sure if I have a simple answer for you, unless you want to throw away the changes you've made since your [last merge](https://github.com/mlworle/Attinderance/pull/4).

If you don't mind loosing that work:

* Switch back to master: `git checkout master`
* Delete this branch locally: `git branch -D mw-create-course`
* Delete this branch on the server: `git push origin :mw-create-course`

Then you can re-make this branch starting from `master`

**Comment by mlworle** [comment]
Did that and got: 
spock@spock-HP-Pavilion-dm1-Notebook-PC:~/rails/Attinderance$ git status
On branch master
Your branch is ahead of 'origin/master' by 16 commits.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean


Should I git push origin master? Also, master branch is throwing errors, while mw-styles is not. Yes there must be something amock.

**Comment by edwardloveall** [comment]
Oh, yes you should always push master up. Duh, I should have thought of that. Makes total sense. You pushed a single new commit to github but when it compares to master, it thinks there are a ton of new commits because they aren't on master yet.

**Comment by mlworle** [comment]
I'm confused.is this right?
$ git chekcout mw-styles    */ since this is the up-to-date branch
$ git push origin mw-styles -f   */ forced because of the rebasing
$ git checkout master
$ git merge mw-styles
$ git push origin master

**Comment by edwardloveall** [comment]
I've seen this before and can't explain it. You pushed up everything to master and repushed the `mw-styles` branch, but it's still showing those old commits. As far as I can tell you've done everything right. The only way to get rid of those extra commits I think is to push a new branch. It looks like you haven't done much of anything so I don't think you'll loose anything. Might be worth it.

**Comment by mlworle** [comment]
ok, no problem. So create a new branch when on the clean working branch? then push that straightaway to master? and merge?
Should there be a pull request somewhere in there?

**Comment by edwardloveall** [comment]
Don't create a branch from anything but `master`. When you crete a branch, it starts from whatever commit you're currently looking at. If you "branch off" of a branch that isn't master, you will be starting from a different place. Later when you try to rebase on master, it will be... weird. It [looks like](https://github.com/mlworle/Attinderance/commits/master) everything is already in master. You can now checkout master, create a new branch, and begin working on whatever feature is next.

**Comment by edwardloveall** [comment]
This might be a helpful read http://www.git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

**Comment by mlworle** [comment]
The new branch mw-clean-up has the same errors, weird code in routes and teacher_controller.rb, etc that was cleaned up on mw-styles. So the last commit must have been dirty. Shall I work on this branch again then merge and continue? Seems like a lot of extra work if one branch is already working.

**Comment by edwardloveall** [comment]
Looks like there were errors in a rebase that we didn't catch. [This commit](https://github.com/mlworle/Attinderance/commit/e77ddbf97c95c1d7906c634cc3a20c62a9bf5323) for example has a bunch. These are called merge conflicts and they are the one downside (among many upsides) to the rebase/merge flow of git.

We could get fancy and try to go back in git history and remove all of this, but my suggestion at this point is to go through and manually remove all the conflicts then commit those changes.

I think all of the conflicts are in the following files:

```
app/assets/stylesheets/static_pages.scss
app/views/static_pages/home.html.erb
config/routes.rb
```

**Comment by mlworle** [comment]
That's what I'm doing now. Good to know for when the projects are bigger and there's more at stake.

**Pull request closed without merging**
