### PR TITLE
password_digest error

### PR DESCRIPTION
**Pull request by mlworle**
getting "undefined method 'password_digest" when running teacher_test.rb.  Should the migration xxxx_add_email_and_password_to_teacher.rb change from 
       add_column :teachers, :password, :string 
to 
       add_column :teachers, :password_digest, :string
?

Here are the errors from the test:

mragy@mragy-Lenovo-IdeaPad-U310-Touch:~/rails/Attinderance$ bundle exec rake test:models
Run options: --seed 41884
# Running:

EEEE...........

Finished in 0.480858s, 31.1942 runs/s, 22.8758 assertions/s.

  1) Error:
TeacherTest#test_name_should_not_be_too_long:
NoMethodError: undefined method `password_digest=' for #<Teacher:0x007f4243902b30>
    test/models/teacher_test.rb:9:in`setup'

  2) Error:
TeacherTest#test_name_should_be_present:
NoMethodError: undefined method `password_digest=' for #<Teacher:0x007f4243961860>
    test/models/teacher_test.rb:9:in`setup'

  3) Error:
TeacherTest#test_name_should_be_unique:
NoMethodError: undefined method `password_digest=' for #<Teacher:0x007f424396ec90>
    test/models/teacher_test.rb:9:in`setup'

  4) Error:
TeacherTest#test_should_be_valid:
NoMethodError: undefined method `password_digest=' for #<Teacher:0x007f42403eb640>
    test/models/teacher_test.rb:9:in`setup'

15 runs, 11 assertions, 0 failures, 4 errors, 0 skips

### CODE REVIEW

**Comment by edwardloveall** [comment]
Hmmm, I do not get those errors. I would suggest maybe resetting your test database?

```shell
rake db:drop db:create db:schema:load RAILS_ENV=test
```

**Comment by mlworle** [comment]
Yuk. No change. This is what I get in the console. No password_digest.
irb(main):001:0> teacher = Teacher.new 
=> #<Teacher id: nil, name: nil, created_at: nil, updated_at: nil, email: nil, password: nil, password_confirmation: nil>

Have leads, though:
http://stackoverflow.com/questions/6069304/activemodelsecurepassword-undefined-method-password-digest
http://stackoverflow.com/questions/6158585/override-validation-error-message-for-securepassword
https://www.railstutorial.org/book/log_in_log_out

And then, the piece-de-resistance:
http://ruby.about.com/od/advancedruby/ss/Cryptographic-Hashes-In-Ruby.htm

I'll keep researching.......

**Comment by edwardloveall** [comment]
Did you add `has_secure_password` to any of your models? If you add that, it requires a `password` field and `password_digest` field in the database, which could lead to this error. I pulled down your code and couldn't find anything.

**Comment by mlworle** [comment]
yes, in app/models/teacher.rb
Does this need a new migration?

**Comment by edwardloveall** [comment]
Hmm I don't see it in the code. Did you not push that up to Github?

In any case, yes, you'll need to migrate `password` to `password_digest` and remove `password_confirmation` all together. I should have caught this before. The idea is you _never ever ever_ store a user's password directly in the database. It must be encrypted (or [digested](https://en.wikipedia.org/wiki/Cryptographic_hash_function)) so that if someone steals your database, they have no passwords.

We can talk about how this works more on Monday if you're curious.

**Comment by mlworle** [comment]
Yep that worked. The docs are helping explain. I'm familiar with academics of SHA encryption, really cool to run into it now!
Thanks!

**Comment by mlworle** [comment]
HI, long time away!
after the last comment, rspec was installed and I started on a user_creates_teacher_spec.rb
this is broken.
it will take a while to fix, too. but isn't it  better to create a new branch?

**Comment by edwardloveall** [comment]
I think user creating a teacher is definitely for another branch.

**Comment by edwardloveall** [comment]
I would get this branch to a point where all the tests pass, even if that means going back in time or removing tests. Then merge it and start a new branch with other features. It's nice to be able to tie off a branch neatly.

**Comment by mlworle** [comment]
Understood, thanks.

**Comment by mlworle** [comment]
Hmm. Getting no method error on 'limit' method in teachers_controller.rb. 
All docs point to ActiveRecord in Rails version 3. Would like to clean this up to close the branch. But maybe reverting to a previous commit is the way to go?

**Comment by edwardloveall** [comment]
So it's definitely because of the `validates(:password` bit in the teacher model. I'm not quite sure how to fix it though (other than removing it).

Here are up-to-date docs: http://api.rubyonrails.org

**Comment by edwardloveall** [comment]
I think also it's getting hung up on the uniqueness validation, which got me thinking "why do passwords need to be unique?" We should be able to have the same password in the system.

Also, it's a security risk because if I type in a password and it tells me that it's taken, I know I can use that password to log into _someone's_ account and that could be used if someone got a hold of the database. Not good.

**Comment by edwardloveall** [comment]
Anyway, in summary, I'd remove the `uniqueness: true` from your password validation in the Teacher model:

```ruby
validates(:password, presence: true, length: {maximum: 10}, format: { with: VALID_PASSWORD_REGEX})
```

**Comment by mlworle** [comment]
HI!!! Happy Holidays! How's it going? 
So I removed the :uniqueness in the teacher model, and cleaned up the tests copied from another app. I think this is ready to close out. 
What do you think?

**Comment by edwardloveall** [comment]
Yeah I'd say if everything passes :+1:

**Pull request merged**
