### PR TITLE
Mw create students

### PR DESCRIPTION
**Pull request by mlworle**
Reversed generated scaffold of create_student. Check to be sure project is clean for creation of Student controller and actions.

### CODE REVIEW

**Comment by edwardloveall** [comment]
Great work! There's only one thing I can find that you forgot because it's tricky to find.

When you `rake db:migrate`, it changes the file `db/schema.rb`. If you look in there you can see some stuff about creating the `create_students` table. This file should never be edited manually, only with migrations. It can go back to its initial state by running `rake db:rollback` but that will try to rollback a migration that you deleted! Quite a conundrum eh?

Here's what to do:

* Create a file in `db/migrations` (you might have to make the migrations folder) called `20150714145356_create_create_students.rb`
* Copy and paste [the old migration](https://github.com/mlworle/Attinderance/blob/524c0426e4f4425874eee8c4cf64c33b2b24d6dc/db/migrate/20150714145356_create_create_students.rb) into it.
* Run `rake db:rollback`. If all goes well, your schema file should look pretty much empty but for some comments and a couple lines of ruby. No `create_table` statements.

After that, push up your changes and I think you'll be good to go!

**Comment by mlworle** [comment]
Ha! Well this is classic. I got bored and played. Here's the sequence:

$ rm -rf Attinderance
  Yep, deleted the whole darn directory. Why? Well not much had been done anyway, so why not start clean? 
$ rails new Attinderance 
$ git add .
$ git commit -m "something"
$ rails generate controller student
$ git add .
$ git commit -m "something"
$ rails generate models student name:string
# decided to change the data model.
# should that be reflected in Trello? 
$ git add .
$ git commit -m "new rails or some such"

Now, the error comes when I try to git push. Here is the code:

spock@spock-HP-Pavilion-dm1-Notebook-PC:~/rails/Attinderance$ git remote
origin
spock@spock-HP-Pavilion-dm1-Notebook-PC:~/rails/Attinderance$ git branch
  master
* mw-create-students
spock@spock-HP-Pavilion-dm1-Notebook-PC:~/rails/Attinderance$ git push origin mw-create-students
To git@github.com:mlworle/Attinderance.git
 ! [rejected]        mw-create-students -> mw-create-students (fetch first)
error: failed to push some refs to 'git@github.com:mlworle/Attinderance.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
spock@spock-HP-Pavilion-dm1-Notebook-

So, continue and fix this one? Go back and fork a branch? Which one? How? Other ideas?

"I mix mathematics and art every day." -Benoit Mandelbrot

Cell: 781-530-7250
Email: mlworle@alumnae.smith.edu
For LinkedIn click here.

**Comment by edwardloveall** [comment]
I think you were actually really close with the other branch. I get the temptation to just wipe the slate clean and start over, but this is actually a good exercise (if not a bit tedious) for when things go wrong farther into a project.

Let's regroup Monday if that's okay and we can get back to that state and take it from there.

**Comment by mlworle** [comment]
Sure! Have a great weekend.

"I mix mathematics and art every day." -Benoit Mandelbrot

Cell: 781-530-7250
Email: mlworle@alumnae.smith.edu
For LinkedIn click here.

**Comment by mlworle** [comment]
Hi, confirming the screen chat at 1:00.
Mara

"I mix mathematics and art every day." -Benoit Mandelbrot

Cell: 781-530-7250
Email: mlworle@alumnae.smith.edu
For LinkedIn click here.

**Comment by edwardloveall** [comment]
Yup 1pm.

**Comment by edwardloveall** [comment]
Looks good to me! Merge away

**Comment by mlworle** [comment]
Done. Now what? New branch to edit/update/destroy student?

**Comment by edwardloveall** [comment]
That sounds like a great next step. Maybe check out and update Trello too to keep that on track

**Pull request merged**
